apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: weavescope
    weavescope-component: weavescope-network-plugin
  name: weavescope-network-plugin
spec:
  template:
    metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-network-plugin
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: weavescope-network-plugin
          image: billyzhang2010/scope-network:latest
          securityContext:
            privileged: true
          volumeMounts:
          - name: scope-plugins
            mountPath: /var/run/scope/plugins
      volumes:
      - name: scope-plugins
        hostPath:
          path: /var/run/scope/plugins
